- name: configure db server
  hosts: mymachines
  become: yes
  vars:
    login_host: 192.168.29.226
  vars_prompt:
  - name: mysql_root_password
    prompt: enter root password for mysql server
    private: false
  tasks:
  - name: install MySql server
    ansible.builtin.yum:
      name: MySql
      state: latest
  - name: start the MySQL service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: true
  - name: install dependencies
    ansible.builtin.pip:
      name: 
      - pymysql
      - cryptography
      executable: pip2.7 
  - name: check DB connection
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{mysql_root_password}}"
      login_host: "{{login_host}}"
      filter: version
      register: mysql_connection_output
  - name: print output
    ansible.builtin.debug:
      msg: "output:{{mysql_connection_output}}"
  - name: setup root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass {{mysql_root_password}}
    when: mysql_connection_output is true

