- name: checking given number
  hosts: mymachines
  vars_prompt:
  - name: number
    prompt: enter any number
    private: false
  tasks:
  - name: "verify whether the given number is less than or greater than or eual to 10"
    ansible.builtin.debug:
      msg: "the number is equal to 10"
    when: number | int == 10

  - name: "to check given number "
    ansible.builtin.debug:
      msg: "given number is greater than 10"
    when: number | int > 10


